---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: usage-engine-private-edition
    releaseName: usage-engine-private-edition
    repo: https://digitalroute-public.github.io/usage-engine-private-edition
    version: 4.2.4
